# Generated by Django 5.1.7 on 2025-04-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='None', max_length=40, verbose_name='Имя')),
                ('image', models.ImageField(upload_to='', verbose_name='картинка')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Имя')),
                ('description_short', models.TextField(blank=True, verbose_name='краткое описание')),
                ('description_long', models.TextField(blank=True, verbose_name='длинное описание')),
                ('lat', models.FloatField(verbose_name='широта')),
                ('lng', models.FloatField(verbose_name='долгота')),
                ('image', models.ManyToManyField(related_name='images', to='places.image', verbose_name='картинки')),
            ],
        ),
    ]
