# Generated by Django 5.1.7 on 2025-04-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Имя'),
        ),
    ]
