# Generated by Django 5.1.7 on 2025-04-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_remove_place_image_image_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
        migrations.AddField(
            model_name='image',
            name='pos',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0, verbose_name='позиция'),
        ),
    ]
