# Generated by Django 5.1.7 on 2025-04-10 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_remove_image_title_image_pos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='pos',
        ),
    ]
