# Generated by Django 5.1.7 on 2025-04-10 17:01

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_remove_image_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(blank=True, verbose_name='длинное описание'),
        ),
    ]
